/* Human sensor library.
 * This converts the raw signal generated by the pyroelectric sensors into a value representing the magnitude of change.
 * The return value is roughly in the range of 0-1000, where higher values indicate more movement.
 * 
 * The noise generated by the human sensor when the robot itself moves is very close to the magnitude of the actual heat signal, so this is near useless unless the robot is sitting still-
 * Possibly more filtering or a better algorythm might resolve this.
 */



//How fast to apply rate of change
#define delta_weight	0.3

//How fast to update baseline value
#define baseline_weight	0.0



//////////


#include <stdio.h>
#include <math.h>

/*
#define magnitude 		1.0
#define threshold		100.0
*/
float lbaseline=2042.0,
	  rbaseline=2042.0;

float ldelta=0,
	  rdelta=0;

float llast,rlast;
	  
/* Compute a magnitude of change for the human sensor data.
 * 
 * float ldelta,rdelta;
 * humanmotion(sensordata->human_left_presence,sensordata->human_right_presence,ldelta,rdelta);
 * 
 */
void humanmotion(float ll,float rr,float &ld,float &rd)
{
	float l=ll-lbaseline,
		  r=rr-rbaseline;
	
	ldelta=abs(l-llast)*delta_weight+ldelta*(1.0-delta_weight);
	rdelta=abs(r-rlast)*delta_weight+rdelta*(1.0-delta_weight);
	
	lbaseline=lbaseline*(1.0-baseline_weight) + ll*baseline_weight;
	rbaseline=rbaseline*(1.0-baseline_weight) + rr*baseline_weight;
	
	ld=ldelta;
	rd=rdelta;
}

void hmdebug()
{
	printf("Baseline: %06.1f|%06.1f Delta: %06.1f|%06.1f\n",lbaseline,rbaseline,ldelta,rdelta);
}
/*
void test()
{
	while(1)
	{
		humanmotion(2000.0,2000.0);
		hmdebug();
		usleep(100000);
	}
}
*/