/* Auto-generated by genmsg_cpp for file /home/drew/git/ycp-robot/MotorControlMsg/msg/MotorCommand.msg */
#ifndef MOTORCONTROLMSG_MESSAGE_MOTORCOMMAND_H
#define MOTORCONTROLMSG_MESSAGE_MOTORCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace MotorControlMsg
{
template <class ContainerAllocator>
struct MotorCommand_ {
  typedef MotorCommand_<ContainerAllocator> Type;

  MotorCommand_()
  : seq(0)
  , stamp()
  , frame_id()
  , precedence(0)
  , linear_velocity(0.0)
  , angular_velocity(0.0)
  {
  }

  MotorCommand_(const ContainerAllocator& _alloc)
  : seq(0)
  , stamp()
  , frame_id(_alloc)
  , precedence(0)
  , linear_velocity(0.0)
  , angular_velocity(0.0)
  {
  }

  typedef uint32_t _seq_type;
  uint32_t seq;

  typedef ros::Time _stamp_type;
  ros::Time stamp;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  frame_id;

  typedef int32_t _precedence_type;
  int32_t precedence;

  typedef float _linear_velocity_type;
  float linear_velocity;

  typedef float _angular_velocity_type;
  float angular_velocity;


private:
  static const char* __s_getDataType_() { return "MotorControlMsg/MotorCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "184e7774b9da63f4a895f16cb3ea4870"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#Standard metadata for higher-level flow data types\n\
#sequence ID: consecutively increasing ID\n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
int32 precedence\n\
\n\
float32 linear_velocity\n\
float32 angular_velocity\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, seq);
    ros::serialization::serialize(stream, stamp);
    ros::serialization::serialize(stream, frame_id);
    ros::serialization::serialize(stream, precedence);
    ros::serialization::serialize(stream, linear_velocity);
    ros::serialization::serialize(stream, angular_velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, seq);
    ros::serialization::deserialize(stream, stamp);
    ros::serialization::deserialize(stream, frame_id);
    ros::serialization::deserialize(stream, precedence);
    ros::serialization::deserialize(stream, linear_velocity);
    ros::serialization::deserialize(stream, angular_velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(seq);
    size += ros::serialization::serializationLength(stamp);
    size += ros::serialization::serializationLength(frame_id);
    size += ros::serialization::serializationLength(precedence);
    size += ros::serialization::serializationLength(linear_velocity);
    size += ros::serialization::serializationLength(angular_velocity);
    return size;
  }

  typedef boost::shared_ptr< ::MotorControlMsg::MotorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::MotorControlMsg::MotorCommand_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MotorCommand
typedef  ::MotorControlMsg::MotorCommand_<std::allocator<void> > MotorCommand;

typedef boost::shared_ptr< ::MotorControlMsg::MotorCommand> MotorCommandPtr;
typedef boost::shared_ptr< ::MotorControlMsg::MotorCommand const> MotorCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::MotorControlMsg::MotorCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::MotorControlMsg::MotorCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace MotorControlMsg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::MotorControlMsg::MotorCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::MotorControlMsg::MotorCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::MotorControlMsg::MotorCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "184e7774b9da63f4a895f16cb3ea4870";
  }

  static const char* value(const  ::MotorControlMsg::MotorCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x184e7774b9da63f4ULL;
  static const uint64_t static_value2 = 0xa895f16cb3ea4870ULL;
};

template<class ContainerAllocator>
struct DataType< ::MotorControlMsg::MotorCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "MotorControlMsg/MotorCommand";
  }

  static const char* value(const  ::MotorControlMsg::MotorCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::MotorControlMsg::MotorCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#Standard metadata for higher-level flow data types\n\
#sequence ID: consecutively increasing ID\n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
int32 precedence\n\
\n\
float32 linear_velocity\n\
float32 angular_velocity\n\
\n\
\n\
";
  }

  static const char* value(const  ::MotorControlMsg::MotorCommand_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::MotorControlMsg::MotorCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.seq);
    stream.next(m.stamp);
    stream.next(m.frame_id);
    stream.next(m.precedence);
    stream.next(m.linear_velocity);
    stream.next(m.angular_velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MotorCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::MotorControlMsg::MotorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::MotorControlMsg::MotorCommand_<ContainerAllocator> & v) 
  {
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "precedence: ";
    Printer<int32_t>::stream(s, indent + "  ", v.precedence);
    s << indent << "linear_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "angular_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MOTORCONTROLMSG_MESSAGE_MOTORCOMMAND_H

